apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2025-05-30T10:51:24Z"
  labels:
    app: spring-petclinic-rest
  name: spring-petclinic-rest
  namespace: default
  resourceVersion: "4125"
  uid: 11a1f322-f069-41de-8fa5-d12e100297cf
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.96.127.210
  clusterIPs:
  - 10.96.127.210
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31408
    port: 9966
    protocol: TCP
    targetPort: 9966
  selector:
    app: spring-petclinic-rest
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
